stdin/stdout hooked up via pipes

diff --git a/kproj/chrisOS/dist/makeall~ b/kproj/chrisOS/dist/makeall~
--- a/kproj/chrisOS/dist/makeall~
+++ b/kproj/chrisOS/dist/makeall~
@@ -1,38 +1,44 @@
 #!/bin/bash
 clear
 echo "Initiating builds"
+mountCmd="sudo mount /dev/disk/by-id/ata-ST31000528AS_5VP8R4ME-part6 /mnt/loop/"
+clean=0
 if [ "$1" != "" ]
 then
-	buildType=$1
+	if [ "$1" == "clean" ]
+	then
+		command="make clean "
+		clean=1
+	else
+		buildType=$1
+		command="make CONF=$buildType build "
+	fi
 else
-	buildType="debug"
+	buildType="Debug"
+	command="make CONF=$buildType build "
 fi
 
-pathMid=dist/${buildType^}/GNU-Linux
+pathMid=dist/${buildType^}/GNU-Linux #GNU-Linux
 
 declare -a kernProgArray=("chrisOS" "chrisOSKernel")
 declare -a kernOutputArray=("chrisOS/$pathMid/chrisos" "chrisOSKernel/$pathMid/kernel")
-declare -a appProgArray=("libChrisOS" "testMainProgramEntry" "kshell" "time" "testMMap")
-declare -a appOutputArray=("libChrisOS/$pathMid/libc.so" "testMainProgramEntry/$pathMid/testmainprogramentry" "kshell/$pathMid/kshell" "time/$pathMid/time" "testMMap/$pathMid/testmmap")
-
-sudo mount /dev/disk/by-id/ata-ST31000528AS_5VP8R4ME-part6 /mnt/loop/
+declare -a appProgArray=("libChrisOS" "testMainProgramEntry" "kshell" "time" "testMMap" "sleep" "cat" "echo")
+declare -a appOutputArray=("libChrisOS/$pathMid/libc.so" "testMainProgramEntry/$pathMid/testmainprogramentry" "kshell/$pathMid/kshell" "time/$pathMid/time" "testMMap/$pathMid/testmmap" "sleep/$pathMid/sleep" "cat/$pathMid/cat" "echo/$pathMid/echo")
 basePath=/home/yogi/src/os/kproj/
-
 tabs 5,36,50,70
-
 echo "Build environment: ${buildType^}"
 echo
 echo "Making kernel projects"
 for i in "${kernProgArray[@]}"
 do
-	cd $basePath/$i/
-	echo "  Make $i"
-	./make_$buildType > /dev/null
+	cd $basePath$i/
+	echo "  Make $i: ($buildType)"
+	($command) > /dev/null
 	if [ $? -eq 0 ] 
 	then
 		echo -en "\tMake $i ... \tsuccess!\n"
 	else
-		echo -en "\tMake $i ... \tfailed\n"
+		echo -en "\tMake $i ... \tfailed ($?)\n"
 		echo 
 		echo 
 		sudo umount /mnt/loop
@@ -41,19 +47,18 @@ do
 	fi
 done
 
-echo
 echo "Making application projects"
 basePath=/home/yogi/src/os/aproj/
 for i in "${appProgArray[@]}"
 do
 	cd $basePath/$i/
-	echo "  Make $i"
-	./make_$buildType > /dev/null
+	echo "  Make $i: ($buildType)"
+	($command) > /dev/null
 	if [ $? -eq 0 ] 
 	then
 		echo -en "\tMake $i ... \tsuccess!\n"
 	else
-		echo "\tMake $i ... \tfailed"
+		echo -en "\tMake $i ... \tfailed"
 		echo 
 		echo 
 		sudo umount /mnt/loop
@@ -63,8 +68,14 @@ do
 done
 
 echo "Done making projects"
+if [ $clean == 1 ] 
+then
+	exit 0
+fi
 echo "Copying output to disk and ISO directory"
+($mountCmd)
 basePath=/home/yogi/src/os/kproj
+
 for i in "${kernOutputArray[@]}"
 do
 	sudo cp $basePath/$i /mnt/loop/
